version: "3.7"
services:
  web:
    build:
      context: ./homehub_web
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./homehub_web:/homehub_web']
  worker:
    build:
      context: celery_workers
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./celery_workers:/queue']
  monitor:
    build:
      context: celery_workers
      dockerfile: Dockerfile.dev
    ports:
     - "5555:5555"
    command:  ['celery', 'flower', '-A', 'tasks']
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis
      - worker
    volumes: ['./celery_workers:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
