name: flake8 check

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 21
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Get python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install flake8
        run: python3 -m pip install flake8

      - uses: liskin/gh-problem-matcher-wrap@v1
        with:
          action: add
          linters: flake8
      - name: flake8
        run: |
          git diff HEAD~1 | flake8 --diff --format=default
      - uses: liskin/gh-problem-matcher-wrap@v1
        if: always()
        with:
          action: remove
          linters: flake8