name: pytest test run

on:
  push:
    branches:
      - master
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 21
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Get python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install pytest
        run: python3 -m pip install pytest

      - name: Install celery-workers requirements
        run: python3 -m pip install -r celery-workers/requirements.txt

      - name: Install homehub_web requirements
        run: python3 -m pip install -r homehub_web/requirements.txt

      - name: Test with pytest
        run: |
            pytest --log-cli-level=10